import { describe, expect, it } from 'vitest'
import { readFileSync, readdirSync, existsSync, statSync } from 'node:fs'
import { join } from 'node:path'
import {
  CURSOR_SIZES,
  CURSOR_SIZE_OPTIONS,
  DEFAULT_CURSOR_SIZE,
} from '../../../src/shared/cursor'

// A cursor that fails to resolve does not throw and does not warn — the browser
// silently falls back to the keyword, so the site just quietly loses its theme.
// These checks are the only thing standing between a typo and that outcome.

const ROOT = process.cwd()
const CSS_PATH = join(ROOT, 'src/styles/cursors.css')
const ART_DIR = join(ROOT, 'public/cursors')

const css = readFileSync(CSS_PATH, 'utf8')
const manifest = JSON.parse(readFileSync(join(ART_DIR, 'manifest.json'), 'utf8')) as {
  cursors: { name: string; hotspot: [number, number]; frames: number; files: string[] }[]
}

function collect(source: string, pattern: RegExp): string[] {
  return [...source.matchAll(pattern)].map((match) => match[1])
}

/** Every .ts, .vue and .css file under src/, so token usage can be checked repo-wide. */
function sourceFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) return sourceFiles(path)
    return /\.(vue|css|ts)$/.test(entry) ? [path] : []
  })
}

describe('cursor artwork references', () => {
  it('resolves every /cursors/ url in the stylesheet to a real file', () => {
    const referenced = collect(css, /url\('\/cursors\/([^']+)'\)/g)
    expect(referenced.length).toBeGreaterThan(0)

    const missing = [...new Set(referenced)].filter((file) => !existsSync(join(ART_DIR, file)))
    expect(missing).toEqual([])
  })

  it('lists every shipped PNG in the manifest', () => {
    const onDisk = readdirSync(ART_DIR).filter((file) => file.endsWith('.png')).sort()
    const declared = manifest.cursors.flatMap((cursor) => cursor.files).sort()
    expect(onDisk).toEqual(declared)
  })

  it('ships every file the manifest declares', () => {
    const missing = manifest.cursors
      .flatMap((cursor) => cursor.files)
      .filter((file) => !existsSync(join(ART_DIR, file)))
    expect(missing).toEqual([])
  })

  it('keeps every hotspot inside the 32x32 cursor', () => {
    // Mapped to names rather than asserted per-cursor so a failure says which.
    const bad = manifest.cursors
      .filter((cursor) => cursor.hotspot.some((value) => value < 0 || value > 31))
      .map((cursor) => `${cursor.name} ${cursor.hotspot.join(',')}`)
    expect(bad).toEqual([])
  })

  it('preserves the animated filmstrips alongside the static frame', () => {
    const animated = manifest.cursors.filter((cursor) => cursor.frames > 1)
    expect(animated.map((cursor) => cursor.name).sort()).toEqual(['busy', 'wait'])

    for (const cursor of animated) {
      expect(cursor.files).toContain(`${cursor.name}-strip.png`)
      expect(cursor.files).toContain(`${cursor.name}-strip@2x.png`)
    }
  })

  it('inlines the default arrow as a decodable PNG data URI, stored once', () => {
    const inlined = collect(css, /url\('data:image\/png;base64,([^']+)'\)/g)
    // Exactly two: the 1x and 2x sources. Every size re-references them through
    // var(), so a third copy means the generator started duplicating ~4.6 KB.
    expect(inlined).toHaveLength(2)

    for (const encoded of inlined) {
      const bytes = Buffer.from(encoded, 'base64')
      expect(bytes.subarray(0, 8)).toEqual(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))
    }
  })

  it('keeps the generator markers intact so the region can be regenerated', () => {
    expect(css).toMatch(/\/\* >>> generated by scripts\/extract-cursors\.py[^\n]*\*\//)
    expect(css).toContain('/* <<< generated */')
  })
})

describe('cursor token wiring', () => {
  const definedCursorTokens = new Set(collect(css, /^\s*(--cursor-[a-z-]+):/gm))
  const definedImageTokens = new Set(collect(css, /^\s*(--img-[a-z0-9-]+):/gm))

  it('defines a keyword fallback for every --cursor-* token', () => {
    // The base :root block must declare all of them outside any media query,
    // otherwise var() goes unresolved on touch and the cursor collapses to auto.
    // Matched as a block rather than sliced to an index, so prose in the header
    // comment cannot shift the boundary.
    const base = css.match(/^:root \{([^}]*)\}/m)
    expect(base).not.toBeNull()
    const baseTokens = new Set(collect(base![1], /\s*(--cursor-[a-z-]+):/g))
    expect([...definedCursorTokens].filter((token) => !baseTokens.has(token))).toEqual([])
  })

  it('resolves every --img-* reference to a defined token', () => {
    const used = new Set(collect(css, /var\((--img-[a-z0-9-]+)\)/g))
    expect([...used].filter((token) => !definedImageTokens.has(token))).toEqual([])
  })

  it('resolves every --cursor-* used across src/ to a defined token', () => {
    const used = new Set<string>()
    for (const file of sourceFiles(join(ROOT, 'src'))) {
      for (const token of collect(readFileSync(file, 'utf8'), /var\((--cursor-[a-z-]+)\)/g)) {
        used.add(token)
      }
    }

    expect(used.size).toBeGreaterThan(0)
    expect([...used].filter((token) => !definedCursorTokens.has(token))).toEqual([])
  })

  it('emits a size block for every size the TypeScript offers, and no others', () => {
    const inCss = [...new Set(collect(css, /\[data-cursor-size='(\d+)'\]/g))].map(Number).sort((a, b) => a - b)
    // The default size is the unqualified block, so it carries no attribute.
    const expected = CURSOR_SIZES.filter((size) => size !== DEFAULT_CURSOR_SIZE).sort((a, b) => a - b)
    expect(inCss).toEqual([...expected])
  })

  it('labels every offered size exactly once', () => {
    expect(CURSOR_SIZE_OPTIONS.map((option) => option.value)).toEqual([...CURSOR_SIZES])
    const labels = CURSOR_SIZE_OPTIONS.map((option) => option.label)
    expect(new Set(labels).size).toBe(labels.length)
  })

  it('scales artwork density and hotspots together for each size', () => {
    // A size block that changed the density but not the hotspot would leave the
    // pointer visibly off-target, which is the failure mode worth guarding.
    const arrowHotspot = manifest.cursors.find((cursor) => cursor.name === 'arrow')!.hotspot

    for (const size of CURSOR_SIZES) {
      const start = size === DEFAULT_CURSOR_SIZE
        ? css.indexOf('@supports (cursor: image-set')
        : css.indexOf(`[data-cursor-size='${size}']`)
      const block = css.slice(start, css.indexOf('}', css.indexOf('--cursor-sw-resize', start)))

      const density = block.match(/--img-ibeam: image-set\([^)]*\) ([\d.]+)x/)
      expect(density, `density for ${size}px`).not.toBeNull()
      expect(Number(density![1])).toBeCloseTo(32 / size, 4)

      if (size === DEFAULT_CURSOR_SIZE) continue
      const hotspot = block.match(/--cursor-default: var\(--img-arrow\) (\d+) (\d+),/)
      expect(hotspot, `hotspot for ${size}px`).not.toBeNull()
      const expectedX = Math.round((arrowHotspot[0] * size) / 32)
      expect(Math.abs(Number(hotspot![1]) - expectedX)).toBeLessThanOrEqual(1)
      expect(Number(hotspot![1])).toBeLessThan(size)
      expect(Number(hotspot![2])).toBeLessThan(size)
    }
  })

  it('leaves no bare cursor keyword behind in a component style', () => {
    // Every declaration must go through a token, or the footer opt-out and the
    // forced-colors bail-out would skip it.
    const offenders: string[] = []
    for (const file of sourceFiles(join(ROOT, 'src'))) {
      if (file === CSS_PATH) continue
      for (const [line] of readFileSync(file, 'utf8').matchAll(/cursor:\s*(?!var\()[a-z-]+;/g)) {
        offenders.push(`${file.slice(ROOT.length)}: ${line}`)
      }
    }
    expect(offenders).toEqual([])
  })
})
